name: thesis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=2.106
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cudatoolkit=11.1.1
  - freetype=2.10.4
  - intel-openmp=2021.2.0
  - jpeg=9b
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.41.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2020.4
  - msys2-conda-epoch=20160418
  - ninja=1.10.2
  - numpy=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.2.0
  - pip=21.0.1
  - python=3.8.8
  - python_abi=3.8
  - pytorch=1.8.0
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - torchaudio=0.8.0
  - torchvision=0.9.0
  - typing_extensions=3.7.4.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - ase==3.21.1
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - googledrivedownloader==0.4
    - h5py==3.2.1
    - idna==2.10
    - isodate==0.6.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - networkx==2.5.1
    - numba==0.53.1
    - pandas==1.2.4
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-louvain==0.15
    - pytz==2021.1
    - rdflib==5.0.0
    - requests==2.25.1
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - six==1.15.0
    - threadpoolctl==2.1.0
    - torch-cluster==1.5.9
    - torch-geometric==1.7.0
    - torch-geometric-temporal==0.27
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9
    - torch-spline-conv==1.2.1
    - tqdm==4.60.0
    - urllib3==1.26.4
